// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// equality
LogicalVector equality(CharacterVector lookupvect, String charstring);
RcppExport SEXP refinr_equality(SEXP lookupvectSEXP, SEXP charstringSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type lookupvect(lookupvectSEXP);
    Rcpp::traits::input_parameter< String >::type charstring(charstringSEXP);
    rcpp_result_gen = Rcpp::wrap(equality(lookupvect, charstring));
    return rcpp_result_gen;
END_RCPP
}
// merge_clusters
CharacterVector merge_clusters(CharacterVector clusters, CharacterVector keys, CharacterVector vect, CharacterVector keyssub, CharacterVector vectsub);
RcppExport SEXP refinr_merge_clusters(SEXP clustersSEXP, SEXP keysSEXP, SEXP vectSEXP, SEXP keyssubSEXP, SEXP vectsubSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type clusters(clustersSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type keys(keysSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type vect(vectSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type keyssub(keyssubSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type vectsub(vectsubSEXP);
    rcpp_result_gen = Rcpp::wrap(merge_clusters(clusters, keys, vect, keyssub, vectsub));
    return rcpp_result_gen;
END_RCPP
}
// most_freq
String most_freq(String clust, CharacterVector keyssub, CharacterVector vectsub);
RcppExport SEXP refinr_most_freq(SEXP clustSEXP, SEXP keyssubSEXP, SEXP vectsubSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type clust(clustSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type keyssub(keyssubSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type vectsub(vectsubSEXP);
    rcpp_result_gen = Rcpp::wrap(most_freq(clust, keyssub, vectsub));
    return rcpp_result_gen;
END_RCPP
}
