# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

merge_KC_clusters <- function(vect, keys_vect, dict, keys_dict) {
    .Call('_refinr_merge_KC_clusters', PACKAGE = 'refinr', vect, keys_vect, dict, keys_dict)
}

ngram_merge_no_approx <- function(n_gram_keys, univect, vect) {
    .Call('_refinr_ngram_merge_no_approx', PACKAGE = 'refinr', n_gram_keys, univect, vect)
}

ngram_merge_approx <- function(n_gram_keys, one_gram_keys, univect, vect, edit_threshold, method, weight, p, bt, q, useBytes, nthread) {
    .Call('_refinr_ngram_merge_approx', PACKAGE = 'refinr', n_gram_keys, one_gram_keys, univect, vect, edit_threshold, method, weight, p, bt, q, useBytes, nthread)
}

cpp_get_char_ngrams <- function(vects, numgram) {
    .Call('_refinr_cpp_get_char_ngrams', PACKAGE = 'refinr', vects, numgram)
}

cpp_tolower <- function(x) {
    .Call('_refinr_cpp_tolower', PACKAGE = 'refinr', x)
}

cpp_paste_list <- function(input, collapse_str) {
    .Call('_refinr_cpp_paste_list', PACKAGE = 'refinr', input, collapse_str)
}

cpp_list_unique <- function(input, sort_vals) {
    .Call('_refinr_cpp_list_unique', PACKAGE = 'refinr', input, sort_vals)
}

remove_strings <- function(input, removes) {
    .Call('_refinr_remove_strings', PACKAGE = 'refinr', input, removes)
}

cpp_unique <- function(vect) {
    .Call('_refinr_cpp_unique', PACKAGE = 'refinr', vect)
}

cpp_trimws_left <- function(vect) {
    .Call('_refinr_cpp_trimws_left', PACKAGE = 'refinr', vect)
}

