# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

merge_KC_clusters_no_dict <- function(clusters, keys_vect, vect, keys_in_clusters) {
    .Call('_refinr_merge_KC_clusters_no_dict', PACKAGE = 'refinr', clusters, keys_vect, vect, keys_in_clusters)
}

merge_KC_clusters_dict <- function(clusters, keys_vect, vect, keys_dict, dict, keys_in_clusters) {
    .Call('_refinr_merge_KC_clusters_dict', PACKAGE = 'refinr', clusters, keys_vect, vect, keys_dict, dict, keys_in_clusters)
}

most_freq <- function(clust, keys_sub, vect_sub) {
    .Call('_refinr_most_freq', PACKAGE = 'refinr', clust, keys_sub, vect_sub)
}

merge_ngram_clusters <- function(clusters, n_gram_keys, univect, vect) {
    .Call('_refinr_merge_ngram_clusters', PACKAGE = 'refinr', clusters, n_gram_keys, univect, vect)
}

get_ngram_initial_clusters <- function(ngram_keys, unigram_keys, unigram_dups) {
    .Call('_refinr_get_ngram_initial_clusters', PACKAGE = 'refinr', ngram_keys, unigram_keys, unigram_dups)
}

filter_initial_clusters <- function(distmatrices, edit_threshold, clusters) {
    .Call('_refinr_filter_initial_clusters', PACKAGE = 'refinr', distmatrices, edit_threshold, clusters)
}

cpp_get_char_ngrams <- function(vects, numgram) {
    .Call('_refinr_cpp_get_char_ngrams', PACKAGE = 'refinr', vects, numgram)
}

cpp_paste_collapse_list <- function(input) {
    .Call('_refinr_cpp_paste_collapse_list', PACKAGE = 'refinr', input)
}

complete_intersect <- function(a, b) {
    .Call('_refinr_complete_intersect', PACKAGE = 'refinr', a, b)
}

cpp_get_key_dups <- function(keys) {
    .Call('_refinr_cpp_get_key_dups', PACKAGE = 'refinr', keys)
}

cpp_in <- function(x, y) {
    .Call('_refinr_cpp_in', PACKAGE = 'refinr', x, y)
}

cpp_list_unique <- function(input, sort_vals) {
    .Call('_refinr_cpp_list_unique', PACKAGE = 'refinr', input, sort_vals)
}

remove_strings <- function(input, removes) {
    .Call('_refinr_remove_strings', PACKAGE = 'refinr', input, removes)
}

equality <- function(lookupvect, charstring) {
    .Call('_refinr_equality', PACKAGE = 'refinr', lookupvect, charstring)
}

cpp_duplicated <- function(vect) {
    .Call('_refinr_cpp_duplicated', PACKAGE = 'refinr', vect)
}

cpp_unique <- function(vect) {
    .Call('_refinr_cpp_unique', PACKAGE = 'refinr', vect)
}

cpp_trimws <- function(vect) {
    .Call('_refinr_cpp_trimws', PACKAGE = 'refinr', vect)
}

